#!/usr/bin/env tsx
// ============================================
// INTERACTIVE SETUP WIZARD
// ============================================
// Run: npm run setup

import * as fs from 'fs';
import * as path from 'path';
import {
  select as inquirerSelect,
  confirm as inquirerConfirm,
  input as inquirerInput,
} from '@inquirer/prompts';

// ============================================
// THEME CONFIGURATION
// ============================================

interface ThemeConfig {
  preset: 'tailwind' | 'shadcn' | 'daisyui' | 'flowbite' | 'headlessui' | 'radixui' | 'preline' | 'nextui';
  primaryColor: 'blue' | 'green' | 'violet' | 'orange' | 'red';
  radius: 'none' | 'small' | 'medium' | 'large';
  darkMode: 'system' | 'light' | 'dark';
}

// HSL color values for each primary color option
const PRIMARY_COLORS = {
  blue: { light: '221 83% 53%', dark: '217 91% 60%' },
  green: { light: '142 76% 36%', dark: '142 69% 58%' },
  violet: { light: '262 83% 58%', dark: '263 70% 50%' },
  orange: { light: '24 95% 53%', dark: '20 90% 48%' },
  red: { light: '0 72% 51%', dark: '0 72% 63%' },
};

const RADIUS_VALUES = {
  none: '0',
  small: '0.25rem',
  medium: '0.5rem',
  large: '0.75rem',
};

function generateGlobalsCss(theme: ThemeConfig): string {
  const primary = PRIMARY_COLORS[theme.primaryColor];
  const radius = RADIUS_VALUES[theme.radius];

  return `@tailwind base;
@tailwind components;
@tailwind utilities;

/* ============================================
   CSS VARIABLES (HSL format for Tailwind)
   ============================================
   Generated by setup wizard. Edit as needed.
   Run \`npm run setup\` to reconfigure.
   ============================================ */

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 0 0% 9%;
    --card: 0 0% 100%;
    --card-foreground: 0 0% 9%;
    --popover: 0 0% 100%;
    --popover-foreground: 0 0% 9%;
    --primary: ${primary.light};
    --primary-foreground: 0 0% 100%;
    --secondary: 0 0% 96%;
    --secondary-foreground: 0 0% 9%;
    --muted: 0 0% 96%;
    --muted-foreground: 0 0% 45%;
    --accent: 0 0% 96%;
    --accent-foreground: 0 0% 9%;
    --destructive: 0 84% 60%;
    --destructive-foreground: 0 0% 100%;
    --border: 0 0% 90%;
    --input: 0 0% 90%;
    --ring: ${primary.light};
    --radius: ${radius};
  }

  .dark {
    --background: 0 0% 4%;
    --foreground: 0 0% 93%;
    --card: 0 0% 7%;
    --card-foreground: 0 0% 93%;
    --popover: 0 0% 7%;
    --popover-foreground: 0 0% 93%;
    --primary: ${primary.dark};
    --primary-foreground: 0 0% 100%;
    --secondary: 0 0% 15%;
    --secondary-foreground: 0 0% 93%;
    --muted: 0 0% 15%;
    --muted-foreground: 0 0% 64%;
    --accent: 0 0% 15%;
    --accent-foreground: 0 0% 93%;
    --destructive: 0 62% 50%;
    --destructive-foreground: 0 0% 100%;
    --border: 0 0% 20%;
    --input: 0 0% 20%;
    --ring: ${primary.dark};
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
    font-feature-settings: "rlig" 1, "calt" 1;
  }
}

/* ============================================
   ANIMATIONS (Framework-agnostic)
   ============================================ */

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
`;
}

function generateComponentsJson(theme: ThemeConfig): string {
  return `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/client/components",
    "utils": "@/lib/utils",
    "ui": "@/client/components/ui",
    "lib": "@/lib",
    "hooks": "@/client/hooks"
  }
}
`;
}

// ============================================
// TAILWIND CONFIG GENERATION
// ============================================

function generateTailwindConfig(preset: ThemeConfig['preset']): string {
  const baseContent = `    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/client/**/*.{js,ts,jsx,tsx,mdx}',`;

  // Additional content paths per preset
  const extraContent: Record<string, string> = {
    flowbite: `\n    './node_modules/flowbite/**/*.js',`,
    preline: `\n    './node_modules/preline/dist/*.js',`,
    nextui: `\n    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',`,
  };

  // Plugin imports per preset
  // DaisyUI and Preline don't ship type declarations, so we use require()
  // Flowbite's subpath export also works better with require()
  // NextUI has proper ESM types
  const pluginImports: Record<string, string> = {
    daisyui: `\n// eslint-disable-next-line @typescript-eslint/no-require-imports\nconst daisyui = require('daisyui');\n`,
    flowbite: `\n// eslint-disable-next-line @typescript-eslint/no-require-imports\nconst flowbite = require('flowbite/plugin');\n`,
    preline: `\n// eslint-disable-next-line @typescript-eslint/no-require-imports\nconst preline = require('preline/plugin');\n`,
    nextui: `\nimport { nextui } from '@nextui-org/theme';\n`,
  };

  // Plugin entries per preset
  const pluginEntries: Record<string, string> = {
    daisyui: 'daisyui',
    flowbite: 'flowbite',
    preline: 'preline',
    nextui: 'nextui()',
  };

  const importLine = pluginImports[preset] ?? '';
  const contentPaths = baseContent + (extraContent[preset] ?? '');
  const pluginEntry = pluginEntries[preset];
  const pluginsArray = pluginEntry ? `[${pluginEntry}]` : '[]';

  return `import type { Config } from 'tailwindcss';
${importLine}
const config: Config = {
  darkMode: 'class',
  content: [
${contentPaths}
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: ${pluginsArray},
};

export default config;
`;
}

// ============================================
// DEPENDENCY INSTALLATION
// ============================================

const PRESET_DEPENDENCIES: Partial<Record<ThemeConfig['preset'], string[]>> = {
  daisyui: ['daisyui'],
  flowbite: ['flowbite', 'flowbite-react'],
  headlessui: ['@headlessui/react'],
  radixui: ['@radix-ui/react-dialog', '@radix-ui/react-dropdown-menu', '@radix-ui/react-tooltip', '@radix-ui/react-popover'],
  preline: ['preline@^2'],
  nextui: ['@nextui-org/react', '@nextui-org/theme', 'framer-motion'],
};

async function installDependencies(preset: ThemeConfig['preset']): Promise<void> {
  const deps = PRESET_DEPENDENCIES[preset];
  if (!deps || deps.length === 0) return;

  const { execSync } = await import('child_process');
  const packages = deps.join(' ');
  console.log(`Installing ${preset} dependencies: ${packages}...`);
  execSync(`npm install ${packages}`, { stdio: 'inherit' });
  console.log(`✓ Installed ${preset} dependencies\n`);
}

// ============================================
// NEXTUI PROVIDER SETUP
// ============================================

function generateProvidersWithNextUI(): string {
  return `'use client';

// ============================================
// APP PROVIDERS
// ============================================
// Wrap the app with all necessary context providers

import { type ReactNode } from 'react';

import { NextUIProvider } from '@nextui-org/react';
import { AuthProvider } from '@/client/lib/auth-context';

interface ProvidersProps {
  children: ReactNode;
}

export function Providers({ children }: ProvidersProps) {
  return (
    <NextUIProvider>
      <AuthProvider>{children}</AuthProvider>
    </NextUIProvider>
  );
}
`;
}

// ============================================
// PRESET DISPLAY NAMES
// ============================================

const PRESET_DISPLAY_NAMES: Record<ThemeConfig['preset'], string> = {
  tailwind: 'Tailwind only',
  shadcn: 'Tailwind + shadcn/ui',
  daisyui: 'Tailwind + DaisyUI',
  flowbite: 'Tailwind + Flowbite',
  headlessui: 'Tailwind + Headless UI',
  radixui: 'Tailwind + Radix UI',
  preline: 'Tailwind + Preline UI',
  nextui: 'Tailwind + NextUI',
};

// ============================================
// SECURITY CONFIGURATION
// ============================================

interface SecurityConfig {
  rateLimit: {
    enabled: boolean;
    login: { maxAttempts: number; windowMs: number };
    api: { maxAttempts: number; windowMs: number };
  };
  lockout: {
    enabled: boolean;
    maxFailedAttempts: number;
    lockoutDurationMs: number;
    showRemainingAttempts: boolean;
  };
  password: {
    minLength: number;
    maxLength: number;
    requireUppercase: boolean;
    requireLowercase: boolean;
    requireNumbers: boolean;
    requireSymbols: boolean;
  };
  session: {
    invalidateOnPasswordChange: boolean;
    maxConcurrentSessions: number | null;
  };
  audit: {
    enabled: boolean;
    storage: 'database' | 'console';
    events: string[];
    retentionDays: number;
  };
}

async function main(): Promise<void> {
  console.log('\n┌─────────────────────────────────────────────────────────────┐');
  console.log('│                                                             │');
  console.log('│   Next.js Starter Setup                                     │');
  console.log('│                                                             │');
  console.log('└─────────────────────────────────────────────────────────────┘\n');

  // Check for .env.local
  const envPath = path.join(process.cwd(), '.env.local');
  const envExamplePath = path.join(process.cwd(), '.env.example');

  if (!fs.existsSync(envPath)) {
    console.log('Creating .env.local from .env.example...\n');

    if (fs.existsSync(envExamplePath)) {
      fs.copyFileSync(envExamplePath, envPath);
      console.log('✓ Created .env.local\n');

      const dbUrl = await inquirerInput({ message: 'Database URL (press Enter for default):' });
      if (dbUrl.trim()) {
        let envContent = fs.readFileSync(envPath, 'utf-8');
        envContent = envContent.replace(
          /DATABASE_URL="[^"]*"/,
          `DATABASE_URL="${dbUrl.trim()}"`
        );
        fs.writeFileSync(envPath, envContent);
      }

      // Generate JWT secret
      const crypto = await import('crypto');
      const jwtSecret = crypto.randomBytes(32).toString('base64');
      let envContent = fs.readFileSync(envPath, 'utf-8');
      envContent = envContent.replace(
        /JWT_SECRET="[^"]*"/,
        `JWT_SECRET="${jwtSecret}"`
      );
      fs.writeFileSync(envPath, envContent);
      console.log('✓ Generated secure JWT_SECRET\n');
    }
  } else {
    console.log('✓ .env.local already exists\n');
  }

  // ============================================
  // UI FRAMEWORK SETUP
  // ============================================

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  UI Framework Setup');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  const themeConfig: ThemeConfig = {
    preset: 'tailwind',
    primaryColor: 'blue',
    radius: 'medium',
    darkMode: 'system',
  };

  themeConfig.preset = await inquirerSelect({
    message: 'Select UI preset:',
    choices: [
      { value: 'tailwind' as const, name: 'Tailwind only (minimal, just utility classes)' },
      { value: 'shadcn' as const, name: 'Tailwind + shadcn/ui (component library with Radix primitives)' },
      { value: 'daisyui' as const, name: 'Tailwind + DaisyUI (Tailwind plugin, themed components)' },
      { value: 'flowbite' as const, name: 'Tailwind + Flowbite (Tailwind plugin + React components)' },
      { value: 'headlessui' as const, name: 'Tailwind + Headless UI (unstyled accessible components by Tailwind Labs)' },
      { value: 'radixui' as const, name: 'Tailwind + Radix UI (unstyled accessible primitives)' },
      { value: 'preline' as const, name: 'Tailwind + Preline UI (Tailwind plugin, interactive components)' },
      { value: 'nextui' as const, name: 'Tailwind + NextUI (Tailwind-based, with Framer Motion)' },
    ],
  });

  themeConfig.primaryColor = await inquirerSelect({
    message: 'Primary color:',
    choices: [
      { value: 'blue' as const, name: 'Blue (default)' },
      { value: 'green' as const, name: 'Green' },
      { value: 'violet' as const, name: 'Violet' },
      { value: 'orange' as const, name: 'Orange' },
      { value: 'red' as const, name: 'Red' },
    ],
  });

  themeConfig.radius = await inquirerSelect({
    message: 'Border radius:',
    choices: [
      { value: 'none' as const, name: 'None (sharp corners)' },
      { value: 'small' as const, name: 'Small (0.25rem)' },
      { value: 'medium' as const, name: 'Medium (0.5rem) - recommended' },
      { value: 'large' as const, name: 'Large (0.75rem)' },
    ],
  });

  themeConfig.darkMode = await inquirerSelect({
    message: 'Dark mode default:',
    choices: [
      { value: 'system' as const, name: 'System (follow OS preference) - recommended' },
      { value: 'light' as const, name: 'Light (always light)' },
      { value: 'dark' as const, name: 'Dark (always dark)' },
    ],
  });

  // Generate globals.css
  const globalsCssPath = path.join(process.cwd(), 'src/app/globals.css');
  fs.writeFileSync(globalsCssPath, generateGlobalsCss(themeConfig));
  console.log('✓ Generated src/app/globals.css\n');

  // Generate tailwind.config.ts based on preset
  const tailwindConfigPath = path.join(process.cwd(), 'tailwind.config.ts');
  fs.writeFileSync(tailwindConfigPath, generateTailwindConfig(themeConfig.preset));
  console.log('✓ Generated tailwind.config.ts\n');

  // If shadcn preset, generate components.json
  if (themeConfig.preset === 'shadcn') {
    const componentsJsonPath = path.join(process.cwd(), 'components.json');
    fs.writeFileSync(componentsJsonPath, generateComponentsJson(themeConfig));
    console.log('✓ Generated components.json (shadcn/ui config)\n');
    console.log('  To add components, run: npx shadcn@latest add button\n');
  }

  // If NextUI preset, update providers.tsx
  if (themeConfig.preset === 'nextui') {
    const providersPath = path.join(process.cwd(), 'src/app/providers.tsx');
    fs.writeFileSync(providersPath, generateProvidersWithNextUI());
    console.log('✓ Updated src/app/providers.tsx with NextUIProvider\n');
  }

  // Install framework-specific dependencies
  await installDependencies(themeConfig.preset);

  // ============================================
  // SECURITY CONFIGURATION
  // ============================================

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  Security Configuration');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  const config: SecurityConfig = {
    rateLimit: {
      enabled: false,
      login: { maxAttempts: 5, windowMs: 60_000 },
      api: { maxAttempts: 100, windowMs: 60_000 },
    },
    lockout: {
      enabled: false,
      maxFailedAttempts: 5,
      lockoutDurationMs: 15 * 60_000,
      showRemainingAttempts: true,
    },
    password: {
      minLength: 8,
      maxLength: 128,
      requireUppercase: false,
      requireLowercase: false,
      requireNumbers: false,
      requireSymbols: false,
    },
    session: {
      invalidateOnPasswordChange: false,
      maxConcurrentSessions: null,
    },
    audit: {
      enabled: false,
      storage: 'database',
      events: [
        'LOGIN_SUCCESS',
        'LOGIN_FAILED',
        'LOGOUT',
        'REGISTER',
        'PASSWORD_CHANGED',
        'ACCOUNT_LOCKED',
        'ACCOUNT_UNLOCKED',
      ],
      retentionDays: 90,
    },
  };

  // Rate Limiting
  config.rateLimit.enabled = await inquirerConfirm({
    message: 'Enable rate limiting? (Prevents brute force attacks)',
    default: true,
  });
  if (config.rateLimit.enabled) {
    const customRate = await inquirerConfirm({ message: 'Use custom rate limits?', default: false });
    if (customRate) {
      const loginMax = await inquirerInput({ message: 'Login max attempts per minute [5]:' });
      if (loginMax.trim()) config.rateLimit.login.maxAttempts = parseInt(loginMax, 10);
      const apiMax = await inquirerInput({ message: 'API max requests per minute [100]:' });
      if (apiMax.trim()) config.rateLimit.api.maxAttempts = parseInt(apiMax, 10);
    }
  }

  // Account Lockout
  config.lockout.enabled = await inquirerConfirm({
    message: 'Enable account lockout? (Lock after failed attempts)',
    default: true,
  });
  if (config.lockout.enabled) {
    const customLockout = await inquirerConfirm({ message: 'Use custom lockout settings?', default: false });
    if (customLockout) {
      const maxAttempts = await inquirerInput({ message: 'Max failed attempts before lockout [5]:' });
      if (maxAttempts.trim()) config.lockout.maxFailedAttempts = parseInt(maxAttempts, 10);
      const duration = await inquirerInput({ message: 'Lockout duration in minutes [15]:' });
      if (duration.trim()) config.lockout.lockoutDurationMs = parseInt(duration, 10) * 60_000;
    }
  }

  // Password Requirements
  const minLen = await inquirerInput({ message: 'Minimum password length [8]:' });
  if (minLen.trim()) config.password.minLength = parseInt(minLen, 10);
  config.password.requireUppercase = await inquirerConfirm({ message: 'Require uppercase letter?', default: false });
  config.password.requireLowercase = await inquirerConfirm({ message: 'Require lowercase letter?', default: false });
  config.password.requireNumbers = await inquirerConfirm({ message: 'Require number?', default: false });
  config.password.requireSymbols = await inquirerConfirm({ message: 'Require symbol?', default: false });

  // Session Security
  config.session.invalidateOnPasswordChange = await inquirerConfirm({
    message: 'Invalidate sessions on password change? (Security best practice)',
    default: true,
  });

  // Audit Logging
  config.audit.enabled = await inquirerConfirm({ message: 'Enable audit logging? (Track security events)', default: true });
  if (config.audit.enabled) {
    config.audit.storage = await inquirerSelect({
      message: 'Storage method:',
      choices: [
        { value: 'database' as const, name: 'Database (recommended)' },
        { value: 'console' as const, name: 'Console only' },
      ],
    });
  }

  // Generate security.ts
  const securityConfigContent = `// ============================================
// SECURITY CONFIGURATION
// ============================================
// Generated by setup wizard. Edit as needed.
// Run \`npm run setup:security\` to reconfigure.

export const security = {
  // ═══════════════════════════════════════════════════════
  // RATE LIMITING
  // ═══════════════════════════════════════════════════════
  rateLimit: {
    enabled: ${config.rateLimit.enabled},
    login: {
      maxAttempts: ${config.rateLimit.login.maxAttempts},
      windowMs: ${config.rateLimit.login.windowMs},
    },
    api: {
      maxAttempts: ${config.rateLimit.api.maxAttempts},
      windowMs: ${config.rateLimit.api.windowMs},
    },
  },

  // ═══════════════════════════════════════════════════════
  // ACCOUNT LOCKOUT
  // ═══════════════════════════════════════════════════════
  lockout: {
    enabled: ${config.lockout.enabled},
    maxFailedAttempts: ${config.lockout.maxFailedAttempts},
    lockoutDurationMs: ${config.lockout.lockoutDurationMs},
    showRemainingAttempts: ${config.lockout.showRemainingAttempts},
  },

  // ═══════════════════════════════════════════════════════
  // PASSWORD REQUIREMENTS
  // ═══════════════════════════════════════════════════════
  password: {
    minLength: ${config.password.minLength},
    maxLength: ${config.password.maxLength},
    requireUppercase: ${config.password.requireUppercase},
    requireLowercase: ${config.password.requireLowercase},
    requireNumbers: ${config.password.requireNumbers},
    requireSymbols: ${config.password.requireSymbols},
  },

  // ═══════════════════════════════════════════════════════
  // SESSION SECURITY
  // ═══════════════════════════════════════════════════════
  session: {
    invalidateOnPasswordChange: ${config.session.invalidateOnPasswordChange},
    maxConcurrentSessions: ${config.session.maxConcurrentSessions},
  },

  // ═══════════════════════════════════════════════════════
  // AUDIT LOGGING
  // ═══════════════════════════════════════════════════════
  audit: {
    enabled: ${config.audit.enabled},
    storage: '${config.audit.storage}' as 'database' | 'console',
    events: [
      'LOGIN_SUCCESS',
      'LOGIN_FAILED',
      'LOGOUT',
      'REGISTER',
      'PASSWORD_CHANGED',
      'ACCOUNT_LOCKED',
      'ACCOUNT_UNLOCKED',
    ] as const,
    retentionDays: ${config.audit.retentionDays},
  },
} as const;

export type SecurityConfig = typeof security;
export type AuditEvent = (typeof security.audit.events)[number];
`;

  const securityPath = path.join(process.cwd(), 'src/config/security.ts');
  fs.writeFileSync(securityPath, securityConfigContent);
  console.log('✓ Generated src/config/security.ts\n');

  // ============================================
  // DATABASE SETUP
  // ============================================

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  Running Database Setup');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  const { execSync } = await import('child_process');

  try {
    console.log('Generating Prisma client...');
    execSync('npx prisma generate', { stdio: 'inherit' });
    console.log('✓ Prisma client generated\n');

    console.log('Pushing database schema...');
    execSync('npx prisma db push', { stdio: 'inherit' });
    console.log('✓ Database schema pushed\n');

    const shouldSeed = await inquirerConfirm({ message: 'Seed database with default roles?', default: true });
    if (shouldSeed) {
      console.log('Seeding database...');
      execSync('npx tsx prisma/seed.ts', { stdio: 'inherit' });
      console.log('✓ Database seeded\n');
    }
  } catch (error) {
    console.error('Database setup failed. Please check your DATABASE_URL in .env.local');
  }

  // ============================================
  // SUMMARY
  // ============================================

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  console.log('✓ Setup complete!\n');

  console.log('UI Framework:');
  console.log(`  • Preset: ${PRESET_DISPLAY_NAMES[themeConfig.preset]}`);
  console.log(`  • Primary color: ${themeConfig.primaryColor}`);
  console.log(`  • Border radius: ${themeConfig.radius}`);
  console.log(`  • Dark mode: ${themeConfig.darkMode}`);
  console.log();

  console.log('Security features:');
  console.log(`  • Rate limiting: ${config.rateLimit.enabled ? '✓' : '✗'}`);
  console.log(`  • Account lockout: ${config.lockout.enabled ? '✓' : '✗'}`);
  console.log(`  • Password rules: min ${config.password.minLength} chars${config.password.requireUppercase ? ', uppercase' : ''}${config.password.requireNumbers ? ', number' : ''}${config.password.requireSymbols ? ', symbol' : ''}`);
  console.log(`  • Session invalidation: ${config.session.invalidateOnPasswordChange ? '✓' : '✗'}`);
  console.log(`  • Audit logging: ${config.audit.enabled ? '✓ (' + config.audit.storage + ')' : '✗'}`);

  console.log('\nNext steps:');
  console.log('  1. Run: npm run dev');
  switch (themeConfig.preset) {
    case 'shadcn':
      console.log('  2. Add components: npx shadcn@latest add button card input');
      break;
    case 'daisyui':
      console.log('  2. Use DaisyUI classes: <button class="btn btn-primary">Click</button>');
      break;
    case 'flowbite':
      console.log("  2. Import components: import { Button } from 'flowbite-react'");
      break;
    case 'headlessui':
      console.log("  2. Import components: import { Dialog, Menu } from '@headlessui/react'");
      break;
    case 'radixui':
      console.log("  2. Import primitives: import * as Dialog from '@radix-ui/react-dialog'");
      break;
    case 'preline':
      console.log('  2. Use Preline classes: <button class="btn btn-primary">Click</button>');
      break;
    case 'nextui':
      console.log("  2. Import components: import { Button } from '@nextui-org/react'");
      break;
  }
  console.log();
}

main().catch((error) => {
  console.error('Setup failed:', error);
  process.exit(1);
});
