#!/usr/bin/env tsx
// ============================================
// INTERACTIVE SETUP WIZARD
// ============================================
// Run: npm run setup

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const question = (prompt: string): Promise<string> =>
  new Promise((resolve) => rl.question(prompt, resolve));

const select = async (prompt: string, options: string[]): Promise<number> => {
  console.log(prompt);
  options.forEach((opt, i) => console.log(`  ${i + 1}) ${opt}`));
  const answer = await question('Enter number: ');
  const index = parseInt(answer, 10) - 1;
  return index >= 0 && index < options.length ? index : 0;
};

const confirm = async (prompt: string, defaultValue = true): Promise<boolean> => {
  const suffix = defaultValue ? '[Y/n]' : '[y/N]';
  const answer = await question(`${prompt} ${suffix}: `);
  if (answer.trim() === '') return defaultValue;
  return answer.toLowerCase().startsWith('y');
};

// ============================================
// THEME CONFIGURATION
// ============================================

interface ThemeConfig {
  preset: 'tailwind' | 'shadcn';
  primaryColor: 'blue' | 'green' | 'violet' | 'orange' | 'red';
  radius: 'none' | 'small' | 'medium' | 'large';
  darkMode: 'system' | 'light' | 'dark';
}

// HSL color values for each primary color option
const PRIMARY_COLORS = {
  blue: { light: '221 83% 53%', dark: '217 91% 60%' },
  green: { light: '142 76% 36%', dark: '142 69% 58%' },
  violet: { light: '262 83% 58%', dark: '263 70% 50%' },
  orange: { light: '24 95% 53%', dark: '20 90% 48%' },
  red: { light: '0 72% 51%', dark: '0 72% 63%' },
};

const RADIUS_VALUES = {
  none: '0',
  small: '0.25rem',
  medium: '0.5rem',
  large: '0.75rem',
};

function generateGlobalsCss(theme: ThemeConfig): string {
  const primary = PRIMARY_COLORS[theme.primaryColor];
  const radius = RADIUS_VALUES[theme.radius];

  return `@tailwind base;
@tailwind components;
@tailwind utilities;

/* ============================================
   CSS VARIABLES (HSL format for Tailwind)
   ============================================
   Generated by setup wizard. Edit as needed.
   Run \`npm run setup\` to reconfigure.
   ============================================ */

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 0 0% 9%;
    --card: 0 0% 100%;
    --card-foreground: 0 0% 9%;
    --popover: 0 0% 100%;
    --popover-foreground: 0 0% 9%;
    --primary: ${primary.light};
    --primary-foreground: 0 0% 100%;
    --secondary: 0 0% 96%;
    --secondary-foreground: 0 0% 9%;
    --muted: 0 0% 96%;
    --muted-foreground: 0 0% 45%;
    --accent: 0 0% 96%;
    --accent-foreground: 0 0% 9%;
    --destructive: 0 84% 60%;
    --destructive-foreground: 0 0% 100%;
    --border: 0 0% 90%;
    --input: 0 0% 90%;
    --ring: ${primary.light};
    --radius: ${radius};
  }

  .dark {
    --background: 0 0% 4%;
    --foreground: 0 0% 93%;
    --card: 0 0% 7%;
    --card-foreground: 0 0% 93%;
    --popover: 0 0% 7%;
    --popover-foreground: 0 0% 93%;
    --primary: ${primary.dark};
    --primary-foreground: 0 0% 100%;
    --secondary: 0 0% 15%;
    --secondary-foreground: 0 0% 93%;
    --muted: 0 0% 15%;
    --muted-foreground: 0 0% 64%;
    --accent: 0 0% 15%;
    --accent-foreground: 0 0% 93%;
    --destructive: 0 62% 50%;
    --destructive-foreground: 0 0% 100%;
    --border: 0 0% 20%;
    --input: 0 0% 20%;
    --ring: ${primary.dark};
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
    font-feature-settings: "rlig" 1, "calt" 1;
  }
}

/* ============================================
   ANIMATIONS (Framework-agnostic)
   ============================================ */

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
`;
}

function generateComponentsJson(theme: ThemeConfig): string {
  return `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/client/components",
    "utils": "@/lib/utils",
    "ui": "@/client/components/ui",
    "lib": "@/lib",
    "hooks": "@/client/hooks"
  }
}
`;
}

// ============================================
// SECURITY CONFIGURATION
// ============================================

interface SecurityConfig {
  rateLimit: {
    enabled: boolean;
    login: { maxAttempts: number; windowMs: number };
    api: { maxAttempts: number; windowMs: number };
  };
  lockout: {
    enabled: boolean;
    maxFailedAttempts: number;
    lockoutDurationMs: number;
    showRemainingAttempts: boolean;
  };
  password: {
    minLength: number;
    maxLength: number;
    requireUppercase: boolean;
    requireLowercase: boolean;
    requireNumbers: boolean;
    requireSymbols: boolean;
  };
  session: {
    invalidateOnPasswordChange: boolean;
    maxConcurrentSessions: number | null;
  };
  audit: {
    enabled: boolean;
    storage: 'database' | 'console';
    events: string[];
    retentionDays: number;
  };
}

async function main(): Promise<void> {
  console.log('\n┌─────────────────────────────────────────────────────────────┐');
  console.log('│                                                             │');
  console.log('│   Next.js Starter Setup                                     │');
  console.log('│                                                             │');
  console.log('└─────────────────────────────────────────────────────────────┘\n');

  // Check for .env.local
  const envPath = path.join(process.cwd(), '.env.local');
  const envExamplePath = path.join(process.cwd(), '.env.example');

  if (!fs.existsSync(envPath)) {
    console.log('Creating .env.local from .env.example...\n');

    if (fs.existsSync(envExamplePath)) {
      fs.copyFileSync(envExamplePath, envPath);
      console.log('✓ Created .env.local\n');

      const dbUrl = await question('Database URL (press Enter for default): ');
      if (dbUrl.trim()) {
        let envContent = fs.readFileSync(envPath, 'utf-8');
        envContent = envContent.replace(
          /DATABASE_URL="[^"]*"/,
          `DATABASE_URL="${dbUrl.trim()}"`
        );
        fs.writeFileSync(envPath, envContent);
      }

      // Generate JWT secret
      const crypto = await import('crypto');
      const jwtSecret = crypto.randomBytes(32).toString('base64');
      let envContent = fs.readFileSync(envPath, 'utf-8');
      envContent = envContent.replace(
        /JWT_SECRET="[^"]*"/,
        `JWT_SECRET="${jwtSecret}"`
      );
      fs.writeFileSync(envPath, envContent);
      console.log('✓ Generated secure JWT_SECRET\n');
    }
  } else {
    console.log('✓ .env.local already exists\n');
  }

  // ============================================
  // UI FRAMEWORK SETUP
  // ============================================

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  UI Framework Setup');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  const themeConfig: ThemeConfig = {
    preset: 'tailwind',
    primaryColor: 'blue',
    radius: 'medium',
    darkMode: 'system',
  };

  const presetIndex = await select('Select UI preset:', [
    'Tailwind only (minimal, just utility classes)',
    'Tailwind + shadcn/ui (component library with Radix primitives)',
  ]);
  themeConfig.preset = presetIndex === 0 ? 'tailwind' : 'shadcn';
  console.log();

  const colorIndex = await select('Primary color:', [
    'Blue (default)',
    'Green',
    'Violet',
    'Orange',
    'Red',
  ]);
  const colorOptions = ['blue', 'green', 'violet', 'orange', 'red'] as const;
  themeConfig.primaryColor = colorOptions[colorIndex] ?? 'blue';
  console.log();

  const radiusIndex = await select('Border radius:', [
    'None (sharp corners)',
    'Small (0.25rem)',
    'Medium (0.5rem) - recommended',
    'Large (0.75rem)',
  ]);
  const radiusOptions = ['none', 'small', 'medium', 'large'] as const;
  themeConfig.radius = radiusOptions[radiusIndex] ?? 'medium';
  console.log();

  const darkModeIndex = await select('Dark mode default:', [
    'System (follow OS preference) - recommended',
    'Light (always light)',
    'Dark (always dark)',
  ]);
  const darkModeOptions = ['system', 'light', 'dark'] as const;
  themeConfig.darkMode = darkModeOptions[darkModeIndex] ?? 'system';
  console.log();

  // Generate globals.css
  const globalsCssPath = path.join(process.cwd(), 'src/app/globals.css');
  fs.writeFileSync(globalsCssPath, generateGlobalsCss(themeConfig));
  console.log('✓ Generated src/app/globals.css\n');

  // If shadcn preset, generate components.json
  if (themeConfig.preset === 'shadcn') {
    const componentsJsonPath = path.join(process.cwd(), 'components.json');
    fs.writeFileSync(componentsJsonPath, generateComponentsJson(themeConfig));
    console.log('✓ Generated components.json (shadcn/ui config)\n');
    console.log('  To add components, run: npx shadcn@latest add button\n');
  }

  // ============================================
  // SECURITY CONFIGURATION
  // ============================================

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  Security Configuration');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  const config: SecurityConfig = {
    rateLimit: {
      enabled: false,
      login: { maxAttempts: 5, windowMs: 60_000 },
      api: { maxAttempts: 100, windowMs: 60_000 },
    },
    lockout: {
      enabled: false,
      maxFailedAttempts: 5,
      lockoutDurationMs: 15 * 60_000,
      showRemainingAttempts: true,
    },
    password: {
      minLength: 8,
      maxLength: 128,
      requireUppercase: false,
      requireLowercase: false,
      requireNumbers: false,
      requireSymbols: false,
    },
    session: {
      invalidateOnPasswordChange: false,
      maxConcurrentSessions: null,
    },
    audit: {
      enabled: false,
      storage: 'database',
      events: [
        'LOGIN_SUCCESS',
        'LOGIN_FAILED',
        'LOGOUT',
        'REGISTER',
        'PASSWORD_CHANGED',
        'ACCOUNT_LOCKED',
        'ACCOUNT_UNLOCKED',
      ],
      retentionDays: 90,
    },
  };

  // Rate Limiting
  config.rateLimit.enabled = await confirm(
    'Enable rate limiting? (Prevents brute force attacks)',
    true
  );
  if (config.rateLimit.enabled) {
    const customRate = await confirm('  Use custom rate limits?', false);
    if (customRate) {
      const loginMax = await question('  Login max attempts per minute [5]: ');
      if (loginMax.trim()) config.rateLimit.login.maxAttempts = parseInt(loginMax, 10);
      const apiMax = await question('  API max requests per minute [100]: ');
      if (apiMax.trim()) config.rateLimit.api.maxAttempts = parseInt(apiMax, 10);
    }
  }
  console.log();

  // Account Lockout
  config.lockout.enabled = await confirm(
    'Enable account lockout? (Lock after failed attempts)',
    true
  );
  if (config.lockout.enabled) {
    const customLockout = await confirm('  Use custom lockout settings?', false);
    if (customLockout) {
      const maxAttempts = await question('  Max failed attempts before lockout [5]: ');
      if (maxAttempts.trim()) config.lockout.maxFailedAttempts = parseInt(maxAttempts, 10);
      const duration = await question('  Lockout duration in minutes [15]: ');
      if (duration.trim()) config.lockout.lockoutDurationMs = parseInt(duration, 10) * 60_000;
    }
  }
  console.log();

  // Password Requirements
  console.log('Password requirements:');
  const minLen = await question('  Minimum length [8]: ');
  if (minLen.trim()) config.password.minLength = parseInt(minLen, 10);
  config.password.requireUppercase = await confirm('  Require uppercase letter?', false);
  config.password.requireLowercase = await confirm('  Require lowercase letter?', false);
  config.password.requireNumbers = await confirm('  Require number?', false);
  config.password.requireSymbols = await confirm('  Require symbol?', false);
  console.log();

  // Session Security
  config.session.invalidateOnPasswordChange = await confirm(
    'Invalidate sessions on password change? (Security best practice)',
    true
  );
  console.log();

  // Audit Logging
  config.audit.enabled = await confirm('Enable audit logging? (Track security events)', true);
  if (config.audit.enabled) {
    const storageIndex = await select('  Storage method:', [
      'Database (recommended)',
      'Console only',
    ]);
    config.audit.storage = storageIndex === 0 ? 'database' : 'console';
  }
  console.log();

  // Generate security.ts
  const securityConfigContent = `// ============================================
// SECURITY CONFIGURATION
// ============================================
// Generated by setup wizard. Edit as needed.
// Run \`npm run setup:security\` to reconfigure.

export const security = {
  // ═══════════════════════════════════════════════════════
  // RATE LIMITING
  // ═══════════════════════════════════════════════════════
  rateLimit: {
    enabled: ${config.rateLimit.enabled},
    login: {
      maxAttempts: ${config.rateLimit.login.maxAttempts},
      windowMs: ${config.rateLimit.login.windowMs},
    },
    api: {
      maxAttempts: ${config.rateLimit.api.maxAttempts},
      windowMs: ${config.rateLimit.api.windowMs},
    },
  },

  // ═══════════════════════════════════════════════════════
  // ACCOUNT LOCKOUT
  // ═══════════════════════════════════════════════════════
  lockout: {
    enabled: ${config.lockout.enabled},
    maxFailedAttempts: ${config.lockout.maxFailedAttempts},
    lockoutDurationMs: ${config.lockout.lockoutDurationMs},
    showRemainingAttempts: ${config.lockout.showRemainingAttempts},
  },

  // ═══════════════════════════════════════════════════════
  // PASSWORD REQUIREMENTS
  // ═══════════════════════════════════════════════════════
  password: {
    minLength: ${config.password.minLength},
    maxLength: ${config.password.maxLength},
    requireUppercase: ${config.password.requireUppercase},
    requireLowercase: ${config.password.requireLowercase},
    requireNumbers: ${config.password.requireNumbers},
    requireSymbols: ${config.password.requireSymbols},
  },

  // ═══════════════════════════════════════════════════════
  // SESSION SECURITY
  // ═══════════════════════════════════════════════════════
  session: {
    invalidateOnPasswordChange: ${config.session.invalidateOnPasswordChange},
    maxConcurrentSessions: ${config.session.maxConcurrentSessions},
  },

  // ═══════════════════════════════════════════════════════
  // AUDIT LOGGING
  // ═══════════════════════════════════════════════════════
  audit: {
    enabled: ${config.audit.enabled},
    storage: '${config.audit.storage}' as 'database' | 'console',
    events: [
      'LOGIN_SUCCESS',
      'LOGIN_FAILED',
      'LOGOUT',
      'REGISTER',
      'PASSWORD_CHANGED',
      'ACCOUNT_LOCKED',
      'ACCOUNT_UNLOCKED',
    ] as const,
    retentionDays: ${config.audit.retentionDays},
  },
} as const;

export type SecurityConfig = typeof security;
export type AuditEvent = (typeof security.audit.events)[number];
`;

  const securityPath = path.join(process.cwd(), 'src/config/security.ts');
  fs.writeFileSync(securityPath, securityConfigContent);
  console.log('✓ Generated src/config/security.ts\n');

  // ============================================
  // DATABASE SETUP
  // ============================================

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  Running Database Setup');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  const { execSync } = await import('child_process');

  try {
    console.log('Generating Prisma client...');
    execSync('npx prisma generate', { stdio: 'inherit' });
    console.log('✓ Prisma client generated\n');

    console.log('Pushing database schema...');
    execSync('npx prisma db push', { stdio: 'inherit' });
    console.log('✓ Database schema pushed\n');

    const shouldSeed = await confirm('Seed database with default roles?', true);
    if (shouldSeed) {
      console.log('Seeding database...');
      execSync('npx tsx prisma/seed.ts', { stdio: 'inherit' });
      console.log('✓ Database seeded\n');
    }
  } catch (error) {
    console.error('Database setup failed. Please check your DATABASE_URL in .env.local');
  }

  // ============================================
  // SUMMARY
  // ============================================

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  console.log('✓ Setup complete!\n');

  console.log('UI Framework:');
  console.log(`  • Preset: ${themeConfig.preset === 'shadcn' ? 'Tailwind + shadcn/ui' : 'Tailwind only'}`);
  console.log(`  • Primary color: ${themeConfig.primaryColor}`);
  console.log(`  • Border radius: ${themeConfig.radius}`);
  console.log(`  • Dark mode: ${themeConfig.darkMode}`);
  console.log();

  console.log('Security features:');
  console.log(`  • Rate limiting: ${config.rateLimit.enabled ? '✓' : '✗'}`);
  console.log(`  • Account lockout: ${config.lockout.enabled ? '✓' : '✗'}`);
  console.log(`  • Password rules: min ${config.password.minLength} chars${config.password.requireUppercase ? ', uppercase' : ''}${config.password.requireNumbers ? ', number' : ''}${config.password.requireSymbols ? ', symbol' : ''}`);
  console.log(`  • Session invalidation: ${config.session.invalidateOnPasswordChange ? '✓' : '✗'}`);
  console.log(`  • Audit logging: ${config.audit.enabled ? '✓ (' + config.audit.storage + ')' : '✗'}`);

  if (themeConfig.preset === 'shadcn') {
    console.log('\nNext steps:');
    console.log('  1. Run: npm run dev');
    console.log('  2. Add components: npx shadcn@latest add button card input');
  } else {
    console.log('\nRun: npm run dev');
  }
  console.log();

  rl.close();
}

main().catch((error) => {
  console.error('Setup failed:', error);
  process.exit(1);
});
